# Generated by Django 4.0.2 on 2022-02-15 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=4)),
                ('publication_house', models.CharField(max_length=15)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.authors')),
            ],
        ),
    ]
